### ISSUE TITLE
Investigate reviving `conda-verify` project as a conda plugin

### ISSUE THREAD

**Issue by beeankha** [conda/conda-verify#123]
### Checklist

- [x] I added a descriptive title
- [x] I searched open issues and couldn't find a duplicate

### What?

Research potentially reviving this project as a plugin allowing package builders to extend package verification functionality.

### Why?

xref: https://github.com/conda/conda-build/issues/5016#issuecomment-2389459021

### User impact

Package builders would be able to extend the build process with additional lint options.

### Goals

- [ ] Decide whether `conda-verify` contains valuable checks/lints
- [ ] Determine whether or not we want to rework this into a plugin hook
